# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2022.3.18-hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/giflib-5.2.1-haf1e3a3_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2021.4.0-hecd8cb5_3538.conda
https://repo.anaconda.com/pkgs/main/osx-64/jpeg-9d-h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libcxx-12.0.0-h2f01273_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-base-1.2.2-hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.3-hca72f7f_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.5-h1de35cc_0.conda
https://conda.anaconda.org/conda-forge/osx-64/yaml-0.2.5-h0d85af4_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.11-h4dc903c_4.conda
https://repo.anaconda.com/pkgs/main/osx-64/brotli-1.0.9-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.3-hb1e8313_2.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lz4-c-1.9.3-h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-2021.4.0-hecd8cb5_637.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1n-hca72f7f_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.1.2-hca72f7f_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.11-h7bc2e8c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.11.0-hd8bbffd_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.37.2-h707629a_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zstd-1.4.9-h322a384_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libtiff-4.2.0-h87d7836_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/python-3.8.10-h88f2d9e_7.conda
https://repo.anaconda.com/pkgs/main/noarch/appdirs-1.4.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/attrs-21.4.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2021.10.8-py38hecd8cb5_2.conda
https://conda.anaconda.org/conda-forge/noarch/cfgv-3.3.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/click-8.0.4-py38hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/distlib-0.3.4-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/filelock-3.6.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/kiwisolver-1.3.2-py38he9d5cce_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/lcms2-2.12-hf1fd2bf_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libwebp-1.2.2-h56c3ce4_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mccabe-0.6.1-py38_1.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mypy_extensions-0.4.3-py38hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/noarch/networkx-2.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pathspec-0.7.0-py_0.conda
https://conda.anaconda.org/conda-forge/noarch/platformdirs-2.5.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pycodestyle-2.7.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.21-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyflakes-2.3.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-3.0.4-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.8-2_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/regex-2021.11.2-py38hca72f7f_0.conda
https://conda.anaconda.org/conda-forge/noarch/six-1.16.0-pyh6c4a22f_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tornado-6.1-py38h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/typed-ast-1.4.3-py38h9ed2024_1.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-4.1.1-pyh06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/black-19.10b0-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/cffi-1.15.0-py38hc55c11b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl-service-2.4.0-py38h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/packaging-21.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pillow-9.0.1-py38hde71d04_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/pyyaml-6.0-py38h96a0964_3.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-58.0.4-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/virtualenv-20.13.4-py38h50d1736_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/flake8-4.0.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/nodeenv-1.6.0-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/numpy-base-1.21.2-py38he0bd621_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pip-21.2.4-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/ukkonen-1.0.1-py38h12bbefe_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/identify-2.4.12-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pre-commit-2.17.0-py38h50d1736_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-3.5.1-py38hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-base-3.5.1-py38hfb0c5b7_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_fft-1.3.1-py38h4ab4a9b_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/mkl_random-1.2.2-py38hb2f4e1b_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/numpy-1.21.2-py38h4b4dc7a_0.conda
